// <auto-generated />
namespace NfiEncomendas.WebServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddSavCustos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSavCustos));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221206572_AddSavCustos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
