// <auto-generated />
namespace NfiEncomendas.WebServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addDataExpedicaoSav : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDataExpedicaoSav));
        
        string IMigrationMetadata.Id
        {
            get { return "202003051018252_addDataExpedicaoSav"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
