// <auto-generated />
namespace NVidrosEncomendas.WebServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removeSetorEncomendaString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeSetorEncomendaString));
        
        string IMigrationMetadata.Id
        {
            get { return "202012141516040_removeSetorEncomendaString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
